### PR TITLE
Bible component refactoring - changed to functional component

### PR DESCRIPTION
**Pull request by SantiagoDePolonia**
- A few components have been created in refactoring to make components smaller
- Bible class component has been changed to more modern functional component with hooks
- A few glitches has been eliminated. Especially those related to using setTimeout to manage with async actions. setTimeout usage has been removed.

Please, do manual testing before merging.

### CODE REVIEW

**Comment by SantiagoDePolonia** [comment]
I reviewed linter errors - looks like the winter don't understand modern JS syntax. False-positives?

**Comment by SantiagoDePolonia** [comment]
Also I reviewed sonarcloud highlights and fixed those reasonable.

**Comment by clash82** [comment]
> I reviewed linter errors - looks like the winter don't understand modern JS syntax. False-positives?

Possible, but this needs to be fixed before merge. How can we do it? Any ideas?

**Comment by SantiagoDePolonia** [comment]
So, is it ready to merge?

**Comment by clash82** [comment]
> So, is it ready to merge?

Not yet. Branch needs to be rebased (avoid merging branches), but it's not that easy, there are too many conflicts to resolve.

**Review by clash82 — APPROVED** [review]
Nice work @SantiagoDePolonia 👍🏻 

I hope you won't mind, but I had to rebase your branch. Linter was also fixed. I did some manual testing and seems that everything work as expected.

**Pull request merged**
